### ISSUE TITLE
Add example output to readme

### ISSUE THREAD

**Issue by disconnect3d** [jhuapl-saralab/tracer#1]
Hey,

could you add an example output to readme?

**Comment by monperrus** [comment]
Would be great to see the JSON resulting from a real build :)

**Comment by smhc** [comment]
I assume this is meant for generating a compile_commands.json database? https://clang.llvm.org/docs/JSONCompilationDatabase.html

If so, this isn't mentioned anywhere.
If not, it might be more useful if it did.

**Comment by myersja** [comment]
An example has been added to the README.  Tracer's output contains much more information than is used in a Clang compilation database, so it should be possible to create a translator which converts Tracer output to a Clang compilation database.

**Comment by monperrus** [comment]
Thanks!
